[2024-07-20 16:23:05,975] 24 root - INFO - data ingestion initiated
[2024-07-20 16:23:05,985] 26 root - INFO - Entered the data ingestion method or component
[2024-07-20 16:23:06,031] 29 root - INFO - Train test split initiated
[2024-07-20 16:23:06,072] 36 root - INFO - Ingestion of data is completed
[2024-07-20 16:23:06,088] 271 root - INFO - Data transformation initiated
[2024-07-20 16:23:06,088] 372 root - ERROR - Error in initialize_data_transformation method: __init__() got an unexpected keyword argument 'sparse'
Traceback (most recent call last):
  File "/Users/apple/Downloads/Ml_Project/ML_project/src/components/data_transformation.py", line 290, in get_data_transformation_object
    ("one_hot_encoder", OneHotEncoder(handle_unknown='ignore', sparse=False))
TypeError: __init__() got an unexpected keyword argument 'sparse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Downloads/Ml_Project/ML_project/src/components/data_transformation.py", line 347, in initialize_data_transformation
    preprocessor_obj = self.get_data_transformation_object()
  File "/Users/apple/Downloads/Ml_Project/ML_project/src/components/data_transformation.py", line 304, in get_data_transformation_object
    raise CustomException(e, sys)
src.exception.CustomException: __init__() got an unexpected keyword argument 'sparse'
